### ISSUE TITLE
Wrong values when simply counting IPs

### ISSUE THREAD

**Issue by lnx1288** [epmcj/bpmapps#1]
Hi,
I'm playing around with BPFabric but can't get it to work properly. I'm basically using the ewma.c example and just adding a HASH map to count the source IPs passing a switch. Sadly it doesn't work. I initialize the counter to 1 (after the first IP packet) correctly but after that, with the second packet it returns a huge weird number (e.g., 140723394557322), although it is correctly incremented afterwards (I mean with the 3rd packet it returns 140723394557323 for example). Any ideas why is this happening? 
Thanks in advance 
Code added to ewma.c examples (excluding the map and struct declarations):

    if (pkt->eth.h_proto == 0x0008) {
        struct ip *ipv4 = (struct ip *)(((uint8_t *)&pkt->eth) + ETH_HLEN);
        struct sips *sip;        
        
        if (bpf_map_lookup_elem(&srcips, &ipv4->ip_src.s_addr, &sip) == 0) {
            sip->sip_count++;
            sip->lasttime = pkt->metadata.sec;
        } else {
            struct sips nsip;
            sip = &nsip;
            sip->sip_count = 1;
            sip->lasttime = pkt->metadata.sec;
            bpf_map_update_elem(&srcips, &ipv4->ip_src.s_addr, &sip, 0);
        }
        bpf_notify(12, sip, sizeof(struct sips));
    }

**Comment by epmcj** [comment]
Hello,
I think your error is when updating the map entry. The function `bpf_map_update_elem` expects a pointer to the value that you want to update and you're passing the address to the pointer. Changing
`bpf_map_update_elem(&srcips, &ipv4->ip_src.s_addr, &sip, 0);`
to 
`bpf_map_update_elem(&srcips, &ipv4->ip_src.s_addr, sip, 0);`
should solve your problem.

**Comment by lnx1288** [comment]
Thanks for your reply, it worked like a charm!
